export const HOME_SIDEBAR = "Home";
export const DATA_UPLOAD_SIDEBAR = "Data Upload";
export const DATA_PROCESS_SIDEBAR = "Data Processing";
export const DEEP_LEARNING_SIDEBAR = "Deep leaning Modeling";
export const HOME_MAIN_TITLE = "TensorMap";
export const HOME_MAIN_CONTENT = "TensorMap is a web application that enables you to create deep learning models " +
    "using a graphical interface without having to know how to code. It is an open-source application."
export const HOME_ABILITY_TITLE = "You can";
export const HOME_ABILITY_CONTENT_1 = "Upload Data for Preprocessing.";
export const HOME_ABILITY_CONTENT_2 = "Make Neural Network Models using Drag and Drop Feature.";
export const HOME_ABILITY_CONTENT_3 = "Visualise uploaded Data.";
export const HOME_ABILITY_CONTENT_4 = "Change Data Columns,Rows etc.";
export const HOME_ABILITY_CONTENT_5 = "Get Generated Code for Neural Network Model Made.";
export const UPLOAD_FILE_TITLE = "Uploaded File Details";
export const UPLOAD_NEW_FILE_TITLE = "Upload New File";
export const UPLOAD_SELECT_FILE_TYPE = "Select File Type";
export const UPLOAD_BUTTON_CONTEXT = "Upload File";
export const UPLOAD_HIDDEN_BUTTON_CONTEXT = "Choose a File";
export const UPLOAD_NEW_FILE_INPUT_LABEL = "File Chosen: ";
export const UPLOAD_NEW_FILE_INPUT_PLACEHOLDER = "Use the above bar to browse your file system";
export const PROCESS_SELECT_FILE_TITLE = "Select the file";
export const PROCESS_SELECT_FILE_FIELD_BEFORE = "First select a file";
export const PROCESS_TARGET_FIELD_SUBMIT_BUTTON = "Add Target Field";
export const PROCESS_SUCCESS_MODEL_MESSAGE = "Target field added successfully";
export const PROCESS_SUCCESS_MODEL_BUTTON = "Got it";
export const PROCESS_FAIL_MODEL_MESSAGE = "Error occurred !!! ";
export const PROCESS_FAIL_MODEL_BUTTON = "Try again";
export const UPLOAD_FILES_LOADING = "Files are Loading ..."
export const UPLOAD_SUCCESS_MODEL_MESSAGE = "File uploaded successfully";
