"""empty message

Revision ID: 4171e479ddd1
Revises: aac9e57a673b
Create Date: 2023-07-21 00:39:38.881148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4171e479ddd1'
down_revision = 'aac9e57a673b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_basic', sa.Column('target_field', sa.String(length=50), nullable=False))
    op.drop_column('model_basic', 'target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_basic', sa.Column('target', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('model_basic', 'target_field')
    # ### end Alembic commands ###
