"""empty message

Revision ID: aac9e57a673b
Revises: afe6f1d0ddf1
Create Date: 2023-07-21 00:12:14.566205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aac9e57a673b'
down_revision = 'afe6f1d0ddf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_basic', sa.Column('file_id', sa.Integer(), nullable=True))
    op.add_column('model_basic', sa.Column('target', sa.String(length=50), nullable=False))
    op.drop_constraint('model_basic_ibfk_1', 'model_basic', type_='foreignkey')
    op.create_foreign_key(None, 'model_basic', 'data_file', ['file_id'], ['id'])
    op.drop_column('model_basic', 'model_dataset')
    op.drop_column('model_basic', 'target_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_basic', sa.Column('target_class', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('model_basic', sa.Column('model_dataset', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_basic', type_='foreignkey')
    op.create_foreign_key('model_basic_ibfk_1', 'model_basic', 'data_file', ['model_dataset'], ['id'])
    op.drop_column('model_basic', 'target')
    op.drop_column('model_basic', 'file_id')
    # ### end Alembic commands ###
