"""empty message

Revision ID: cdbaf30dfba7
Revises: cf6c4c54da67
Create Date: 2021-05-21 23:27:13.124416

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cdbaf30dfba7"
down_revision = "cf6c4c54da67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_process",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target", sa.String(length=10), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["data_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_process")
    # ### end Alembic commands ###
