const styles = theme => ({
	container: {
	    position: 'absolute',
	    left: '40%',
	    top: '20%'
  	},
  	text: {
		width: '100%',
		padding: '12px 20px',
		margin: '8px 0',
		display: 'inline-block',
		border: '1px solid #ccc',
		borderRadius: '4px',
		boxSizing: 'border-box'
  	},
  	submit: {
		width: '100%',
		color: 'white',
		backgroundColor: 'green',
		padding: '14px 20px',
		margin: '8px 0',
		border: 'none',
		cursor: 'pointer',
  	},
  	browse: {
		width: '100%',
		color: 'white',
		backgroundColor: 'white',
		padding: '14px 20px',
		margin: '8px 0',
		border: 'none',
		cursor: 'pointer',
  	},
  	datatable: {
  		borderCollapse: 'collapse',
		width: '100%',
  	},
  	datatabletd: {
		border: '1px solid #ddd',
		padding: '8px',
  	},
  	datatableth: {
		border: '1px solid #ddd',
		padding: '8px',
		paddingTop: '12px',
  		paddingBottom: '12px',
  		textAlign: 'left',
  		backgroundColor: '#4CAF50',
  		color: 'white',
  	},
  	editbtn: {
		backgroundColor: 'grey',
		border: 'none',
		color: 'white',
		padding: '5px 10px',
		textAlign: 'center',
		textDecoration: 'none',
		display: 'inline-block',
		fontSize: '15px',
		margin: '4px 2px',
		cursor: 'pointer',
		borderRadius: '5px',
  	},
  	savebtn: {
		backgroundColor: 'grey',
		border: 'none',
		color: 'white',
		padding: '5px 10px',
		textAlign: 'center',
		textDecoration: 'none',
		display: 'inline-block',
		fontSize: '15px',
		margin: '4px 2px',
		cursor: 'pointer',
		borderRadius: '5px',
  	},
  	hidden: {
  		display: 'none',
  	},
  	canbtn: {
		backgroundColor: 'grey',
		border: 'none',
		color: 'white',
		padding: '5px 10px',
		textAlign: 'center',
		textDecoration: 'none',
		display: 'inline-block',
		fontSize: '15px',
		margin: '4px 2px',
		cursor: 'pointer',
		borderRadius: '5px',
  	},
  	viewbtn: {
		backgroundColor: '#008CBA',
		border: 'none',
		color: 'white',
		padding: '5px 10px',
		textAlign: 'center',
		textDecoration: 'none',
		display: 'inline-block',
		fontSize: '15px',
		margin: '4px 2px',
		cursor: 'pointer',
		borderRadius: '5px',
  	},
  	delbtn: {
		backgroundColor: 'red',
		border: 'none',
		color: 'white',
		padding: '5px 10px',
		textAlign: 'center',
		textDecoration: 'none',
		display: 'inline-block',
		fontSize: '15px',
		margin: '4px 2px',
		cursor: 'pointer',
		borderRadius: '5px',
  	},
  	pagination: {
  		display: 'inline-block',
  		position: 'absolute',
  		left: '40%',
  	},
  	paginationbtn: {
		color: 'black',
		float: 'left',
		fontWeight: '3px',
		padding: '8px 16px',
		textDecoration: 'none',
		border: '2px solid #ddd',
		borderRadius: '5px',
		cursor: 'pointer',
  	},
  	paginationbtnactive: {
		color: 'black',
		backgroundColor: '#4CAF50',
		float: 'left',
		fontWeight: '3px',
		padding: '8px 16px',
		textDecoration: 'none',
		border: '2px solid #ddd',
		borderRadius: '5px',
		cursor: 'pointer',
  	}
})

export default styles
